Traceback (most recent call last):
  File "/home/josteines/.venv/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/josteines/.venv/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/josteines/.venv/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/josteines/.venv/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/josteines/.venv/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/josteines/.venv/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# how to open data when downloaded from the staging page: https://data-staging.met.no/metsis/elements/no-met-staging-e19b9c36-a9dc-4e13-8827-c998b9045b54/search

# Get the path of the home directory
home_dir = os.path.expanduser("~")

# Use os.path.join to combine paths
path2files = os.path.join(home_dir, "Downloads") # "Dowloads" --> path to files

# Specify something to recognice the desired nc-files, extract them and put them in a list
desired_files_paths = glob.glob(os.path.join(path2files, "ASA_*.nc"))
# print(desired_files_paths)

''' ###################### To uncomment this snippet place the marker here and press: ctrl + k + c. To comment it out again press: ctrl + k + u ####################

# Create a list of desired files
files2open = []
for i in range(len(desired_files_paths)):
    ith_file = desired_files_paths[i].replace(path2files+'/', '')
    print(ith_file)
    files2open.append(ith_file)

print(files2open)
#'''

# Open the first dataset
ds = xr.open_dataset(desired_files_paths[0])
# print(desired_files_paths[0])

# Interactive overview of the dataset
ds
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mIndexError[0m                                Traceback (most recent call last)
Cell [0;32mIn[4], line 26[0m
[1;32m     13[0m [38;5;124;03m''' ###################### To uncomment this snippet place the marker here and press: ctrl + k + c. To comment it out again press: ctrl + k + u ####################[39;00m
[1;32m     14[0m 
[1;32m     15[0m [38;5;124;03m# Create a list of desired files[39;00m
[0;32m   (...)[0m
[1;32m     22[0m [38;5;124;03mprint(files2open)[39;00m
[1;32m     23[0m [38;5;124;03m#'''[39;00m
[1;32m     25[0m [38;5;66;03m# Open the first dataset[39;00m
[0;32m---> 26[0m ds [38;5;241m=[39m xr[38;5;241m.[39mopen_dataset([43mdesired_files_paths[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m)
[1;32m     27[0m [38;5;66;03m# print(desired_files_paths[0])[39;00m
[1;32m     28[0m 
[1;32m     29[0m [38;5;66;03m# Interactive overview of the dataset[39;00m
[1;32m     30[0m ds

[0;31mIndexError[0m: list index out of range

